Repository AutoMQ/automq, pull requests merged in 2024-02, with the labels that each got.

#778 feat(telemetry): make metrics dashboard compatible with Aliyun
  core/src/main/resources/jmx/rules/broker.yaml
  core/src/main/resources/jmx/rules/common.yaml
  core/src/main/scala/kafka/log/stream/s3/telemetry/TelemetryManager.java
  docker/telemetry/grafana/provisioning/dashboards/Developer/detailed.json
  docker/telemetry/grafana/provisioning/dashboards/User/broker.json
  docker/telemetry/grafana/provisioning/dashboards/User/cluster.json
  docker/telemetry/grafana/provisioning/dashboards/User/group.json
  docker/telemetry/grafana/provisioning/dashboards/User/topic.json
Labels: enhancement

#821 fix(ReplicaManager): fix memory leak caused by uncaught exception
  core/src/main/scala/kafka/server/ReplicaManager.scala
Labels: bug

#828 fix(pr-827): fix release `PooledMemoryRecords` twice
  clients/src/main/java/org/apache/kafka/common/network/KafkaChannel.java
Labels: bug

#831 fix(ReplicaManager): release permits after sending responses
  clients/src/main/java/org/apache/kafka/common/record/PooledRecords.java
  core/src/main/scala/kafka/cluster/Partition.scala
  core/src/main/scala/kafka/server/DelayedFetch.scala
  core/src/main/scala/kafka/server/ReplicaManager.scala
Labels: enhancement

#844 perf(DelayedFetch): only try to fast read on complete a delayed fetch
  core/src/main/scala/kafka/server/DelayedFetch.scala
  core/src/main/scala/kafka/server/ReplicaManager.scala
Labels: perf

#845 perf(ReplicaManager): return fast if slow fetch timeout
  core/src/main/scala/kafka/server/ReplicaManager.scala
Labels: perf
