Repository AutoMQ/automq, pull requests merged in 2024-01, with the labels that each got.

#651 perf: return fast when the `fetchOffset` equals to the `confirmOffset`
  core/src/main/scala/kafka/cluster/Partition.scala
Labels: enhancement

#656 revert: perf: return fast when the `fetchOffset` equals to the `confirmOffset`
  core/src/main/scala/kafka/cluster/Partition.scala
Labels: bug

#658 perf: return fast when the `fetchOffset` equals to the `confirmOffset`
  core/src/main/scala/kafka/cluster/Partition.scala
  core/src/main/scala/kafka/log/streamaspect/ElasticUnifiedLog.scala
  core/src/main/scala/kafka/server/ReplicaManager.scala
Labels: enhancement

#659 perf: check the last segment first to avoid calling `floorSegment`
  core/src/main/scala/kafka/log/CachedLogSegments.scala
  core/src/main/scala/kafka/log/UnifiedLog.scala
  core/src/main/scala/kafka/log/streamaspect/ElasticLog.scala
Labels: enhancement

#669 perf: allocate less in `readFromLocalLogV2`
  core/src/main/scala/kafka/cluster/Partition.scala
  core/src/main/scala/kafka/log/CachedLogSegments.scala
  core/src/main/scala/kafka/log/streamaspect/DefaultElasticStreamSlice.java
  core/src/main/scala/kafka/server/DelayedFetch.scala
  core/src/main/scala/kafka/server/ReplicaManager.scala
Labels: enhancement

#670 feat(tool): add admin tool to help user start AutoMQ easily
  bin/automq-kafka-admin.sh
  bin/kafka-run-class.sh
  build.gradle
  checkstyle/import-control-automq.xml
  checkstyle/import-control-core.xml
  checkstyle/import-control.xml
  core/src/main/java/kafka/s3shell/util/EnvUtil.java
  core/src/main/java/kafka/s3shell/util/KafkaFormatUtil.java
  core/src/main/java/kafka/s3shell/util/S3ShellPropUtil.java
  core/src/main/scala/kafka/Kafka.scala
  core/src/main/scala/kafka/tools/StorageTool.scala
  core/src/test/java/kafka/s3shell/util/S3ShellPropUtilTest.java
  core/src/test/scala/unit/kafka/KafkaConfigTest.scala
  gradle/dependencies.gradle
  s3shell-kafka-sdk/src/main/java/com/automq/s3shell/sdk/constant/ServerConfigKey.java
  s3shell-kafka-sdk/src/main/java/com/automq/s3shell/sdk/model/AuthMethod.java
  s3shell-kafka-sdk/src/main/java/com/automq/s3shell/sdk/model/EndpointProtocol.java
  s3shell-kafka-sdk/src/main/java/com/automq/s3shell/sdk/model/S3Url.java
  s3shell-kafka-sdk/src/main/java/com/automq/s3shell/sdk/util/S3PropUtil.java
  s3shell-kafka-sdk/src/main/resources/template/broker.properties
  s3shell-kafka-sdk/src/main/resources/template/controller.properties
  s3shell-kafka-sdk/src/main/resources/template/server.properties
  settings.gradle
  tools/src/main/java/org/apache/kafka/tools/automq/AutoMQKafkaAdminTool.java
  tools/src/main/java/org/apache/kafka/tools/automq/GenerateConfigFileCmd.java
  tools/src/main/java/org/apache/kafka/tools/automq/GenerateS3UrlCmd.java
  tools/src/main/java/org/apache/kafka/tools/automq/GenerateStartCmdCmd.java
  tools/src/main/java/org/apache/kafka/tools/automq/model/ServerGroupConfig.java
  tools/src/main/java/org/apache/kafka/tools/automq/util/ConfigParserUtil.java
  tools/src/test/java/org/apache/kafka/tools/automq/GenerateConfigFileCmdTest.java
  tools/src/test/java/org/apache/kafka/tools/automq/GenerateS3UrlCmdTest.java
  tools/src/test/java/org/apache/kafka/tools/automq/model/S3UrlTest.java
  tools/src/test/java/org/apache/kafka/tools/automq/util/ConfigParserUtilTest.java
Labels: AKIP
